### ISSUE TITLE
Bug: Lavalauncher doesn't exit on the exit command

### ISSUE THREAD

**Issue by snakedye** [Leon-Plickat/LavaLauncher#3]

**Comment by Leon-Plickat** [comment]
Thanks for the report. Not a bug in the code (it was never more than a developer feature, so I removed it when I redesigned the way commands are executed) but in the documentation.

**Comment by snakedye** [comment]
Is there a similar command? I wanted to make a power bar (lock, logout, etc..) and close lavalauncher once the the power command was executed.

**Comment by Leon-Plickat** [comment]
Ah, I see.

When I started LavaLauncher, I actually had that use case in mind, but over time have come to the conclusion that LavaLauncher is not the right program for this task. My intention is to eventually add some sort of menu widget thing to LavaLauncher, which should take care of this use case.

In the mean time, I will re-add the 'exit' and 'reload' commands temporarily.
